In [4]:
import pandas as pd

df = pd.read_csv('State - Seamless Region Map 20210429.csv')
df

state_region = {
    'AL': 'S',
    'AR': 'S',
    'AZ': 'S',
    'CA': 'S',
    'CO': 'W',
    'CT': 'C',
    'DE': 'C',
    'FL': 'S',
    'GA': 'S',
    'IA': 'N',
    'ID': 'W',
    'IL': 'N',
    'IN': 'N',
    'KS': 'W',
    'KY': 'N',
    'LA': 'S',
    'MA': 'C',
    'MD': 'C',
    'ME': 'C',
    'MI': 'N',
    'MN': 'N',
    'MO': 'N',
    'MS': 'S',
    'MT': 'W',
    'NC': 'S',
    'ND': 'W',
    'NE': 'W',
    'NH': 'C',
    'NJ': 'C',
    'NM': 'S',
    'NV': 'S',
    'NY': 'C',
    'OH': 'N',
    'OK': 'S',
    'OR': 'S',
    'PA': 'C',
    'RI': 'C',
    'SC': 'S',
    'SD': 'W',
    'TN': 'S',
    'TX': 'S',
    'UT': 'W',
    'VA': 'C',
    'WA': 'S',
    'WI': 'N',
    'WV': 'C',
    'WY': 'W'
}

   State SeamlessRegion
0     AL              S
1     AR              S
2     AZ              S
3     CA              S
4     CO              W
5     CT              C
6     DE              C
7     FL              S
8     GA              S
9     IA              N
10    ID              W
11    IL              N
12    IN              N
13    KS              W
14    KY              N
15    LA              S
16    MA              C
17    MD              C
18    ME              C
19    MI              N
20    MN              N
21    MO              N
22    MS              S
23    MT              W
24    NC              S
25    ND              W
26    NE              W
27    NH              C
28    NJ              C
29    NM              S
30    NV              S
31    NY              C
32    OH              N
33    OK              S
34    OR              S
35    PA              C
36    RI              C
37    SC              S
38    SD              W
39    TN              S
40    TX              S
41    UT              W
42    VA              C
43    VT              C
44    WA              S
45    WI              N
46    WV              C
47    WY              W